/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGraficaPVsZ3;

import Clases.User;
import Clases.Validation;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class Registro extends javax.swing.JFrame implements Serializable{

    private PantallaPrincipal pp;

    /**
     * Creates new form Registro
     */
    public Registro(PantallaPrincipal PP) {
        this.pp = PP;
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelRegistro = new java.awt.Panel();
        JButtonVolver = new javax.swing.JButton();
        JLabelNOMBRE = new javax.swing.JLabel();
        JLabelDNI = new javax.swing.JLabel();
        JButtonAceptarNuevoUsuario = new javax.swing.JButton();
        JTextFieldNombre = new javax.swing.JTextField();
        JTextFieldDNI = new javax.swing.JTextField();
        JLabelLG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        JPanelRegistro.setBackground(new java.awt.Color(51, 51, 51));

        JButtonVolver.setBackground(new java.awt.Color(102, 0, 0));
        JButtonVolver.setText("Volver");
        JButtonVolver.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonVolverActionPerformed(evt);
            }
        });

        JLabelNOMBRE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        JLabelNOMBRE.setText("Nombre");

        JLabelDNI.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        JLabelDNI.setText("DNI");

        JButtonAceptarNuevoUsuario.setBackground(new java.awt.Color(153, 153, 153));
        JButtonAceptarNuevoUsuario.setText("Aceptar");
        JButtonAceptarNuevoUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JButtonAceptarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAceptarNuevoUsuarioActionPerformed(evt);
            }
        });

        JTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));

        JTextFieldDNI.setBackground(new java.awt.Color(255, 255, 255));

        JLabelLG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPVsZ3/shovel.png"))); // NOI18N

        javax.swing.GroupLayout JPanelRegistroLayout = new javax.swing.GroupLayout(JPanelRegistro);
        JPanelRegistro.setLayout(JPanelRegistroLayout);
        JPanelRegistroLayout.setHorizontalGroup(
            JPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelRegistroLayout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addGroup(JPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelRegistroLayout.createSequentialGroup()
                        .addGroup(JPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JButtonAceptarNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(297, 297, 297))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelRegistroLayout.createSequentialGroup()
                        .addGroup(JPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLabelDNI)
                            .addComponent(JLabelNOMBRE))
                        .addGap(87, 87, 87)
                        .addGroup(JPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTextFieldNombre)
                            .addComponent(JTextFieldDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelRegistroLayout.createSequentialGroup()
                        .addComponent(JLabelLG)
                        .addGap(321, 321, 321))))
        );
        JPanelRegistroLayout.setVerticalGroup(
            JPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelRegistroLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(JLabelLG, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(JPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(JPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(JButtonAceptarNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.pp.setVisible(true);
    }//GEN-LAST:event_JButtonVolverActionPerformed

    private void JButtonAceptarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAceptarNuevoUsuarioActionPerformed
        /**
         * Recogerá los datos que se hayan introducido por JTextFieldNombre y
         * JTextFieldDNI.
         */
        Serializacion.cargarDatos();
        String username = JTextFieldNombre.getText().trim().toUpperCase(); // Almacenamos el nombre. Lo pasamos a mayúsculas para almacenar los nombres.
        String user_dni = JTextFieldDNI.getText().trim().toUpperCase(); // Almacenamos DNI de igual manera.
        if (fieldsFill(username, user_dni)) {
            boolean exist_username = searchUsername(username);     
            if (exist_username) JOptionPane.showMessageDialog(new JFrame(), "Usuario registrado. Cámbialo o inicia sesión.", "AVISO: Nombre repetido", JOptionPane.WARNING_MESSAGE); 
            else {
                boolean exist_DNI = searchDni(user_dni);
                if(exist_DNI) JOptionPane.showMessageDialog(new JFrame(), "DNI ya incluido. Cámbialo o inicia sesión.", "AVISO: DNI repetido", JOptionPane.WARNING_MESSAGE);
                else {
                    registerUser(username, user_dni);
                }
            }
        }
    }//GEN-LAST:event_JButtonAceptarNuevoUsuarioActionPerformed

    public boolean fieldsFill (String username, String dni){
        
        if (username.equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe de incluir nombre", "AVISO: Campo vacío", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if(dni.equals("")){
            JOptionPane.showMessageDialog(new JFrame(), "Debe de incluir DNI", "AVISO: Campo vacío", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
        
    }
    
    public boolean searchUsername(String username){
        for (User u : Serializacion.getUsuarios().keySet()) {
            if (u.getUsername().equalsIgnoreCase(username)) {
                return true;
            }
        }
        return false;
    }
    
    public boolean searchDni(String dni){
        for (User u : Serializacion.getUsuarios().keySet()) {
            if (u.getDni().equalsIgnoreCase(dni)) {
                return true;
            }
        }
        return false;
    }
    
    public void registerUser(String username, String dni){
        Validation v = new Validation();
        if(v.canBeIntroduced(Serializacion.getUsuarios(), dni)){
            User u = new User(username, dni);
            Serializacion.guardarUsuario(u);
            JOptionPane.showMessageDialog(new JFrame(), "Usuario registrado correctamente. \nNúmero usuarios registrados: "+Serializacion.getUsuarios().size(), "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAceptarNuevoUsuario;
    private javax.swing.JButton JButtonVolver;
    private javax.swing.JLabel JLabelDNI;
    private javax.swing.JLabel JLabelLG;
    private javax.swing.JLabel JLabelNOMBRE;
    private java.awt.Panel JPanelRegistro;
    private javax.swing.JTextField JTextFieldDNI;
    private javax.swing.JTextField JTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
